from .test_avg_pool1d_op import *
from .test_avg_pool2d_op import *
from .test_avg_pool3d_op import *
from .test_conv1d_op import *
from .test_conv2d_op import *
from .test_conv3d_op import *
from .test_max_pool1d_op import *
from .test_max_pool2d_op import *
from .test_max_pool3d_op import *
