from .test_array_slice_op import *
from .test_as_strided_op import *
from .test_detach_op import *
from .test_expand_op import *
from .test_imag_op import *
from .test_pad_op import *
from .test_permute_op import *
from .test_real_op import *
from .test_squeeze_op import *
from .test_unsqueeze_op import *
from .test_view_as_imag_op import *
from .test_view_as_real_op import *
from .test_view_op import *
